name: Build Multi-Platform Binaries

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake gcc-multilib
          if [ "${{ matrix.arch }}" = "aarch64" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi

      - name: Configure and Build
        run: |
          ./configure
          if [ "${{ matrix.arch }}" = "aarch64" ]; then
            make CC=aarch64-linux-gnu-gcc
          else
            make
          fi

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dns2tcp-linux-${{ matrix.arch }}
          path: |
            client/dns2tcpc
            server/dns2tcpd

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-autotools
            make
            
      - name: Configure and Build
        shell: msys2 {0}
        run: |
          ./configure
          make
          
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dns2tcp-windows-${{ matrix.arch }}
          path: |
            client/dns2tcpc.exe
            server/dns2tcpd.exe 