name: Build Multi-Platform Binaries

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool

      - name: Build x86_64
        run: |
          autoreconf -fi
          CFLAGS="-g -O2 -Wall -Wextra -Werror=implicit-function-declaration" ./configure
          make
          mkdir -p artifacts/linux-x86_64
          cp client/dns2tcpc server/dns2tcpd artifacts/linux-x86_64/

      - name: Setup ARM64 cross-compilation
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          make clean
          CFLAGS="-g -O2 -Wall -Wextra -Werror=implicit-function-declaration" ./configure --host=aarch64-linux-gnu
          make CC=aarch64-linux-gnu-gcc
          mkdir -p artifacts/linux-arm64
          cp client/dns2tcpc server/dns2tcpd artifacts/linux-arm64/

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dns2tcp-linux
          path: artifacts/*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-autotools
            autoconf
            automake
            libtool
            make
            
      - name: Build x64
        shell: msys2 {0}
        run: |
          autoreconf -fi
          CFLAGS="-g -O2 -Wall -Wextra -Werror=implicit-function-declaration" ./configure --host=x86_64-w64-mingw32
          make
          mkdir -p artifacts/windows-x64
          cp client/dns2tcpc.exe server/dns2tcpd.exe artifacts/windows-x64/
          
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dns2tcp-windows
          path: artifacts/* 